<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXGuJD9b\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXGuJD9b/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXGuJD9b.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXGuJD9b\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXGuJD9b\App_KernelDevDebugContainer([
    'container.build_hash' => 'XGuJD9b',
    'container.build_id' => 'ea32dfcb',
    'container.build_time' => 1618903028,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXGuJD9b');
