<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOs8UuBy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOs8UuBy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOs8UuBy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOs8UuBy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOs8UuBy\App_KernelDevDebugContainer([
    'container.build_hash' => 'Os8UuBy',
    'container.build_id' => '301e2ba4',
    'container.build_time' => 1618845564,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOs8UuBy');
